# Site settings
title: "Sofia Sampaio - Currículo"
description: "Licenciada em Turismo | Currículo Profissional"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sofia Sampaio"
resume_title:                   "Licenciada em Turismo"

resume_contact_email:           "sofiasampaio18@gmail.com"

resume_contact_telephone:       "963 329 055"
resume_contact_address:         "Porto, Portugal"

resume_header_contact_info:     "Porto, Portugal • 963 329 055 • sofiasampaio18@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Sou recém-licenciada em Turismo pela Universidade de Trás-os-Montes e Alto Douro. Estou sempre preparada para novos desafios, com uma paixão especial na área de turismo. Procuro sempre aprender mais e alcançar com excelência tudo o que faço.</p>"

resume_looking_for_work:        "yes"

# Sections
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true   # repurposed for Extra-Curricular
resume_section_skills:          true
resume_section_recognition:     false  # hide if not needed
resume_section_links:           false
resume_section_associations:    false
resume_section_languages:       true
# resume_section_interests:     true

# Social links (add your real ones)
resume_social_links:
  resume_linkedin_url:          "https://linkedin.com/in/mariasofia-sampaio"
  resume_website_url:           "https://sofiasampaio18.github.io/Curriculum-vitae/"   # optional
  # resume_github_url, etc.

resume_print_social_links:      true

resume_theme:                   default